server:
  port: 8080
spring:
  datasource:
    password: helloworld
    url: jdbc:postgresql://localhost:5433/liandfung
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: truegit
    show-sql: true